out_dir: datasets/whisper_features
feature_extraction_parts:
  - life
  - figures
  - bourne
  - wolf
  - chaplin
  - mononoke
  - passepartout
  - planetearth
  - wot
  - pulpfiction
  - s1
  - s2
  - s3
  - s4
  - s5
  - s6
  - s7

model: openai/whisper-large-v3
layers:
  - layer_norm
  - layers.31.fc2
  - layers.25.fc2
  - layers.12.fc2

datasets_root: /data
splits_overlap: 0.5
past_context: 20

overwrite: true
seed: 42
device: cuda
