out_dir: datasets/features.sharded

model: vit_giant_patch14_reg4_dinov2.lvd142m
layers:
  - blocks.*5
grid_size: 5

batch_size: 64

datasets_root: /data

overwrite: false
num_workers: 16
seed: 42
device: cuda
