out_dir: null

features:
  - model: internvl3_8b_8bit
    layer: language_model.model.layers.20.post_attention_layernorm

  - model: whisper
    layer: layers.12.fc2

  - model: meta-llama__Llama-3.2-1B
    layer: model.layers.7
    stem: context-long

test_set_name: friends-s7

datasets_root: null

overwrite: false
device: cuda
