out_dir: output/feature_encoding

model:
  embed_dim: 192
  encoder_kernel_size: 33
  decoder_kernel_size: 0
  hidden_model: null
  global_pool: avg
  encoder_causal: false
  encoder_positive: false
  encoder_blockwise: false
  pool_num_heads: 3
  with_shared_decoder: true
  with_subject_decoders: true

transformer:
  num_heads: 3
  depth: 6
  mlp_ratio: 4.0

conv1dnext:
  depth: 6
  kernel_size: 11
  causal: false

features:
  internvl3_8b/layers.20:
    model: internvl3_8b_8bit
    layer: language_model.model.layers.20.post_attention_layernorm
  
  internvl3_8b/layers.10:
    model: internvl3_8b_8bit
    layer: language_model.model.layers.10.post_attention_layernorm

  internvl3_14b/layer.30:
    model: internVL3_14B
    layer: language_model.model.layers.30.post_attention_layernorm

  qwen-2-5-omni-7b/layers.20:
    model: qwen-2-5-omni-7b
    layer: model.layers.20.post_attention_layernorm
  
  qwen-2-5-omni-3b/layers.20:
    model: qwen2-5_3B
    layer: model.layers.20.post_attention_layernorm

  whisper/layers.12:
    model: whisper
    layer: layers.12.fc2
   
  whisper/layers.31:
    model: whisper
    layer: layers.31.fc2

  MFCC/audio:
    model: MFCC
    layer: audio
    
  llama_3.2_1b/layers.7:
    model: meta-llama__Llama-3.2-1B
    layer: model.layers.7
    stem: context-long
  
  llama_3.2_1b/layers.15:
    model: meta-llama__Llama-3.2-1B
    layer: model.layers.15
    stem: context-long

  dinov2/blocks.5:
    model: vit_giant_patch14_reg4_dinov2.lvd142m
    layer: blocks.5

  dinov2/blocks.15:
    model: vit_giant_patch14_reg4_dinov2.lvd142m
    layer: blocks.15

  dinov2/blocks.25:
    model: vit_giant_patch14_reg4_dinov2.lvd142m
    layer: blocks.25

  dinov2/blocks.35:
    model: vit_giant_patch14_reg4_dinov2.lvd142m
    layer: blocks.35

  dinov2/embedding:
    model: vit_giant_patch14_reg4_dinov2.lvd142m
    layer: embedding
  
  dinov2-giant/pooler_output:
    model: dinov2-giant
    layer: pooler_output
    
  vjepa2/encoder.layernorm_avg:
    model: vjepa2_avg_feat
    layer: encoder.layernorm_avg

include_features:
  - internvl3_8b/layers.20
  - whisper/layers.12
  - llama_3.2_1b/layers.7

datasets:
  train:
    filter:
      seasons: [1, 2, 3, 4, 5]
      movies: ["bourne", "wolf"]
    sample_length: 64
    num_samples: 2000
    shuffle: True
    seed: 42

  val_s6:
    filter:
      seasons: [6]
      movies: []
    sample_length: null
    num_samples: null
    shuffle: false

  val_figures:
    filter:
      seasons: []
      movies: ["figures"]
    sample_length: null
    num_samples: null
    shuffle: false

  val_life:
    filter:
      seasons: []
      movies: ["life"]
    sample_length: null
    num_samples: null
    shuffle: false

batch_size: 16
lr: 3e-4
weight_decay: 0.1
epochs: 10

checkpoint: null
freeze_decoder: false

datasets_root: null

seed: 3315
overwrite: false
device: cuda