out_dir: datasets/qwen2-5_3B
feature_extraction_parts:
  - life
  - figures
  - bourne
  - wolf
  - chaplin
  - mononoke
  - passepartout
  - planetearth
  - wot
  - pulpfiction
  - s1
  - s2
  - s3
  - s4
  - s5
  - s6
  - s7

model: Qwen/Qwen2.5-Omni-3B
layers:
  - model.layers.15.post_attention_layernorm
  - model.layers.20.post_attention_layernorm

datasets_root: /data
splits_overlap: 0.5
past_context: 20

overwrite: true
seed: 42
device: cuda
